export enum Role {
  STUDENT = 'STUDENT',
  INSTRUCTOR = 'INSTRUCTOR',
  ADMIN = 'ADMIN',
}

export enum EnrollmentStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  DROPPED = 'DROPPED',
}

export enum QuestionType {
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  TRUE_FALSE = 'TRUE_FALSE',
  MULTIPLE_ANSWER = 'MULTIPLE_ANSWER',
  SHORT_ANSWER = 'SHORT_ANSWER',
}

export enum AttemptStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  ABANDONED = 'ABANDONED',
}

export enum ActivityType {
  LESSON_COMPLETED = 'LESSON_COMPLETED',
  QUIZ_COMPLETED = 'QUIZ_COMPLETED',
  COURSE_COMPLETED = 'COURSE_COMPLETED',
}

export enum RecommendationType {
  REVIEW_TOPIC = 'REVIEW_TOPIC',
  TAKE_QUIZ = 'TAKE_QUIZ',
  ENROLL_COURSE = 'ENROLL_COURSE',
}

export enum RecommendationStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  DISMISSED = 'DISMISSED',
}

export enum NotificationType {
  QUIZ_RESULT = 'QUIZ_RESULT',
  WEAK_TOPIC_DETECTED = 'WEAK_TOPIC_DETECTED',
  RECOMMENDATION_READY = 'RECOMMENDATION_READY',
  COURSE_MILESTONE = 'COURSE_MILESTONE',
  INSTRUCTOR_ALERT = 'INSTRUCTOR_ALERT',
}

export enum DraftStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PUBLISHED = 'PUBLISHED',
}
